### ISSUE TITLE
私有部署使用exportjson数据无法导入，服务端报错ER_NO_DEFAULT_FOR_FIELD

### ISSUE THREAD

**Issue by nisiyu** [NEIAPI/nei#35]
1. 在NEI公有地址把项目exportjson下载下来
2. 本地私有化部署了NEI，docker-compose 启动
3. 创建项目并且导入json失败，显示了待导入的接口，但最终报了错，导入失败。

```
[E] [2021-07-21 04:33:49.964] - ER_NO_DEFAULT_FOR_FIELD: Field 'type' doesn't have a default value
[E] [2021-07-21 04:33:50.406] -
meta -> {"message":"domain is not defined","stack":"ReferenceError: domain is not defined\n    at dumpName (/appops/server/service/helper/notification.js:140:32)\n    at dumpTextAndToUsers (/appops/server/service/helper/notification.js:175:18)\n    at dumpTextAndToUsers.next (<anonymous>)\n    at onFulfilled (/appops/node_modules/co/index.js:65:19)\n    at /appops/node_modules/co/index.js:54:5\n    at new Promise (<anonymous>)\n    at co (/appops/node_modules/co/index.js:50:10)\n    at toPromise (/appops/node_modules/co/index.js:118:63)\n    at next (/appops/node_modules/co/index.js:99:29)\n    at onFulfilled (/appops/node_modules/co/index.js:69:7)"}
```

因为这个导入页面没有权限限制，我没办法公开提供我的key作为输入数据。

**Comment by huntbao** [comment]
导入功能没有在私有化部署版本中实现，请自己实现
